### ISSUE TITLE
Plugins Using Reflection Causes Error

### ISSUE THREAD

**Issue by BungeeTheCookie** [CyberdyneCC/Thermos#336] opened 2016-04-29 14:33 UTC
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))* http://pastebin.com/MC5vW5Gq
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))* http://pastebin.com/xYFp4gev

**Explanation of issue:** Hello Thermos community! Several plugins (that utilize Reflection libraries or such utilities) are erroring, most notably TuxTwoLib, MassiveCore, and PlotSquared. TuxTwoLib and MassiveCore I downloaded from Robotia's Fixes, so I'm not sure why they are erroring. Is there anyway this can be fixed? Thanks!

**How to recreate this issue:** Download a clean installation of Thermos and install the plugins listed with their corresponding versions (essentials uses latest, TuxTwoLib uses build from Robotia's tixes, PlotSquared uses latest version, MassiveCore uses Robotia's fixes, Multiverse-Core is latest version, Factions uses version that is the same of MassiveCore's, MultiInv uses the 1.7 version, CS-CoreLib and Slimefun use the one before the 1.9-only version of the plugin)

**Modpack Name:** *(Only if public)*

**Mods Installed:** None [Clean Server Installation to Demonstrate Mods Do Not Cause This Error]

**Plugins Installed:** Essentials, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, TuxTwoLib, PlotSquared, EssentialsSpawn, MassiveCore, Multiverse-Core, Factions, VanishNoPacket, MultiInv, CS-CoreLib, MassiveBooks, Slimefun

**Warmroast Report:** *(Optional)*

**Thermos Version:** 55

**Forge Version:** 1614

**Comment by Robotia** [comment] 2016-04-29 14:56
The crash is because you don't have the TuxTwoLib plugin: `Caused by: java.lang.NoClassDefFoundError: Tux2/TuxTwoLib/attributes/Attributes`

The particles issue is a known issue that probably won't be fixed due to its complexity.

**Comment by BungeeTheCookie** [comment] 2016-04-29 15:10
Thank you for responding so quickly! The issue regarding PlotSquared isn't that major is it?
Also, I am pretty sure TuxTwoLib is loaded, as it is in my plugins folder and when I run /plugins it indicates that TuxTwoLib is installed.

**Comment by Robotia** [comment] 2016-04-29 15:20
@BungeeTheCookie http://gogs.tcpr.ca/TCPR/Fixes/raw/df3d50f6506b797efaa90c80e5e754f7642bfc89/TuxTwoLib/TuxTwoLib.jar use that TuxTwoLib.

**Comment by BungeeTheCookie** [comment] 2016-04-29 16:39
It is still erroring, after I use that TuxTwoLib.

**Comment by BungeeTheCookie** [comment] 2016-04-29 16:56
Nevermind, I solved it. Thanks!

**Closed** 2016-04-29 17:32 UTC
