### ISSUE TITLE
Cannot find main class error

### ISSUE THREAD

**Issue by MeGysssTaa** [CyberdyneCC/Thermos#453] opened 2016-07-20 18:03 UTC
**Server Log:** http://pastebin.com/c6LkBxcG

**FML Log(s):** -

**Explanation of issue:** Some plugin does not run due to error 'cannot find main class'. If using normal Bukkit / Spigot, it will run ok.

**How to recreate this issue:** Try to run the plugin Reflex (AC).

**Modpack Name:** *(Only if public)* -

**Mods Installed:** -

**Plugins Installed:** Reflex, ProtocolLib

**Warmroast Report:** *(Optional)* -

**Thermos Version:** 1.7.10 Theroms 1614 Build 57

**Forge Version:** -

**Comment by Time6628** [comment] 2016-07-20 19:36
Why are you trying to run an anti-cheat plugin on a modded server...?

**Comment by MeGysssTaa** [comment] 2016-07-20 21:17
I'm not trying to do that. I'm the dev, and one guy sent me this info. The problem doesn't occur on Bukkit / Spigot, so I think it's Thermos fault ._.

**Comment by Time6628** [comment] 2016-07-20 21:24
Do you use any NMS in your plugin?

**Comment by MeGysssTaa** [comment] 2016-07-21 06:16
Yes, for getting player ping.

**Comment by Time6628** [comment] 2016-07-21 06:30
That is most likely the cause.

**Comment by MeGysssTaa** [comment] 2016-07-21 06:40
NMS is called only when player is fighting suspiciously to check is he lagging. But plugin can't be even enabled because it cannot find main class.

**Comment by spannerman79** [comment] 2016-07-21 08:15
From what I understand on how MCPC+/Cauldron (and its forks) is that classes are dynamic - there is no static link to the class in question.

From memory (don't quote as I don't remember fully or properly on this) this is needed as there are some classes that do the same function within forge and bukkit just with different named classes - hence why the class/es is/are dynamic and not static.

**Comment by MeGysssTaa** [comment] 2016-07-22 10:14
So how to fix that then?

**Comment by spannerman79** [comment] 2016-07-22 10:15
https://github.com/CyberdyneCC/Thermos/issues/353#issuecomment-229095980

**Comment by Robotia** [comment] 2016-08-13 03:26
The pastebin is no longer valid: `This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.`

Assuming this issue had been resolved by OP.

**Closed by Robotia** 2016-08-13 03:26 UTC
