### ISSUE TITLE
Random crash using Thermos and RTG

### ISSUE THREAD

**Issue by Eufranio** [CyberdyneCC/Thermos#565] opened 2016-10-31 20:04 UTC
Sometimes, in my server, when players are generating new chunks, the server randomly crashes. It won't happen always, seems to be random...

**How to recreate this issue:**

Walk, walk and walk.

**Modpack Name:** [Here](http://www.technicpack.net/modpack/magitech-server-1710.820227)
**Plugins**: (47): 
```
aUCVault, Itemizer, WorldEdit, OpenInv, Offline_Teleporter, BetterChunkLoader, ClearLag, AutoMessage, PlugMan, VipZeroFIX, Votifier, ConsoleSpamFix, ProtocolLib, WorldGuard, AutoSaveWorld, MagiUtils, MultiWorld, ChatReaction, eZProtector, AsyncWorldEdit, UUIDFetcher, SimpleORM, VIPSlots, PermissionsEx, Magi-GUI, Vault, MyCommand, BungeeTabListPlus, BetterAlias, ItemRestrict, FastLogin, xKit, Essentials, ScoreboardStats, Trading, RandomTP, HolographicDisplays, VipZero, Citizens, Legendchat, TagsGUI-2.0, ChestCommands, DiscordSRV, FramePicture, EssentialsSpawn, AuthMe, AuthMeBridge
```

Thermos build 58, Forge 1614
RTG 1.7.10-1.1.1

**Comment by Time6628** [comment] 2016-11-01 01:57
Dupe of https://github.com/CyberdyneCC/Thermos/issues/486 I believe.

**Closed by Time6628** 2016-11-01 01:57 UTC
