### ISSUE TITLE
PlayerChangedWorldEvent & PlayerTeleportEvent return wrong from locations

### ISSUE THREAD

**Issue by NDruce** [CyberdyneCC/Thermos#349] opened 2016-05-08 17:28 UTC
**Server Log:** http://pastebin.com/HutD6dTt

**FML Log(s):** not required

**Explanation of issue:** When player teleports between worlds, he actually teleports with no errors, but debugging show me about this is false, and there are bug exists. So (if you see the code of Multiverse), players don't charge money for switching worlds and too more don't work. Actually Multiverse-Inventory doesn't switches inventories and all players able to get items from Creative-worlds for free and take it to Survival world. IT IS VERY HARMFUL FOR SERVER (ex. using ghast spawn eggs in Overworld) AND ECONOMY! But it must be fixed at least because it is broken.

**How to recreate this issue:** Fix world teleport event to 'WorldTeleportedFrom<->WorldTeleportedTo' not equals

**Modpack Name:** not required

**Mods Installed:** not required

**Plugins Installed:** Multiverse-Core v2.5-b697 (latest for 1.7.10), Multiverse-Inventories v2.5-b383 (latest for 1.7.10), Vault, PermissionsEx

**Warmroast Report:** none

**Thermos Version:** 56

**Forge Version:** 1614

**Comment by NDruce** [comment] 2016-05-08 17:43
When you done please share me fixed class for Thermos 56, because I can't wait it too long. Thanks

**Comment by spannerman79** [comment] 2016-05-08 17:45
Try build 55. 56 is pre release as stated.

Secondly if you want it fixed in a hurry pay a java developer. Otherwise wait patiently

**Comment by NDruce** [comment] 2016-05-08 18:28
On 55 the same error

**Comment by Time6628** [comment] 2016-05-08 18:33
You're teleporting to the same world you are already in.

**Comment by NDruce** [comment] 2016-05-08 18:37
Ohhh... Are you kidding me? I say about it is bug, and about I actually teleport in other world (I can quote me), but event tells about it is false. You can see log, it is even different world names in MV debug

**Comment by Time6628** [comment] 2016-05-08 18:41
Nevermind, didn't see that you teleported to plot first.

**Comment by NDruce** [comment] 2016-05-08 18:55
I'we teleported from plot to world firstly, then vice versa - from world to plot. World alias is &f, plot alias is [Plot] (it's for chat formatting firstly)

**Comment by NDruce** [comment] 2016-05-08 18:57
Not Plot, [Плот]

**Comment by NDruce** [comment] 2016-05-08 19:04
http://pastebin.com/E75kNyRG
Just use '/mv debug 3' and test yourself

**Comment by Time6628** [comment] 2016-05-08 20:40
Multiverse is known to be very buggy. Try this multiworld plugin https://www.spigotmc.org/resources/multiworld.4598/

**Comment by NDruce** [comment] 2016-05-08 20:46
He is not very buggy, instead. I sometime runned Multiworld on modded server and it was full of errors. Besides, Multiverse is most comfortable than it. Bug is only one and only on Thermos, because it works fine on Cauldron Reloaded #1291. I'll try to check event methods in custom plugin, then report you.

**Comment by NDruce** [comment] 2016-05-08 20:57
One second... Hm, I guess! It is because MV compares world objects, not world names. But it strange because that issue only on Thermos...

**Comment by spannerman79** [comment] 2016-05-08 20:59
Instead of writing several comments you can edit previous comment if you just want to add one sentence.  Otherwise it becomes too long of a string.

**Comment by NDruce** [comment] 2016-05-08 22:02
You can remove 'External' tag, bug approved.
`	@EventHandler
	public void asd(PlayerChangedWorldEvent e) {
		Player p = e.getPlayer();
		p.sendMessage("§2[§eFrom "+e.getFrom().getName()+"§2] §f"+e.getFrom().toString());
		p.sendMessage("§2[§eTo "+p.getWorld().getName()+"§2] §f"+p.getWorld().toString());
	}
![image](https://cloud.githubusercontent.com/assets/3519015/15100682/b00a35d2-1581-11e6-8a40-8462b3b3f41c.png)
`

**Comment by Time6628** [comment] 2016-05-09 00:02
This event hasn't been modified what so ever.

**Comment by Robotia** [comment] 2016-05-09 00:08
MultiverseInventory, Он больше не используется ...
осуждается

**Comment by NDruce** [comment] 2016-05-09 00:08
And therefore this don't needed to fix? It BUG, and it expected. **There are with any plugins.** It can't get world! If it not Bukkit event error, so this error in another code, for example NMS (net.minecraft.server) or Thermos with getting world player teleported from. I writed code above for testing.

**Comment by NDruce** [comment] 2016-05-09 00:09
@Robotia, you able to write? I say about this bug with ANY plugin, even MultiInv and PerWorldInventory!

**Comment by Robotia** [comment] 2016-05-09 00:11
Вы смотрите для mod for inventory?

**Comment by NDruce** [comment] 2016-05-09 00:12
You have bad Russian, I don't understand you)

**Comment by NDruce** [comment] 2016-05-09 00:42
[ChangeWorldDebug](https://www.dropbox.com/s/07sdezlpyorubps/ChangeWorldDebug.jar?dl=1) plugin for you

**Comment by Robotia** [comment] 2016-05-09 00:48
(((
Sorry, you are right about the bug.
Prostil? :stuck_out_tongue:

**Comment by NDruce** [comment] 2016-05-09 00:49
Ya i ne obizhalsya ;)

**Comment by Robotia** [comment] 2016-05-09 00:53
:+1: We will investigate

**Comment by NDruce** [comment] 2016-05-09 01:18
Cauldron with Forge 1231
![image](https://cloud.githubusercontent.com/assets/3519015/15101598/03762d1e-159d-11e6-8407-e590bf04c613.png)

**Comment by Bogdan-G** [comment] 2016-05-09 10:27
не ну, я понимаю тот русский текст что пишет Robotia xD

---

@NDruce search version where no bug

**Comment by NDruce** [comment] 2016-05-09 16:48
![image](https://cloud.githubusercontent.com/assets/3519015/15120553/f52d3b30-161e-11e6-9c67-100f84518d20.png)

BROKEN cauldron-1.7.10-1.1343.01.0.zip
BROKEN cauldron-1.7.10-1.1291.01.0.zip
**FINE cauldron-1.7.10-1.1307.06.218.zip**

![2016-05-09_18 40 51](https://cloud.githubusercontent.com/assets/3519015/15120478/8a24518e-161e-11e6-8934-faa13582c7e3.png)
![2016-05-09_18 27 55](https://cloud.githubusercontent.com/assets/3519015/15120476/8a235838-161e-11e6-9c11-b8f489618a6c.png)
![2016-05-09_18 30 04](https://cloud.githubusercontent.com/assets/3519015/15120479/8a285e5a-161e-11e6-9af8-e0d35926bd67.png)
![2016-05-09_18 37 51](https://cloud.githubusercontent.com/assets/3519015/15120477/8a23e0a0-161e-11e6-8507-adc940034f36.png)

**Comment by Bogdan-G** [comment] 2016-05-10 14:15
>> Official Cauldron git-ver +fake Forge version, meh, strange, which versions and from whom they are.

**Comment by NDruce** [comment] 2016-05-10 15:24
What?

**Comment by Robotia** [comment] 2016-05-10 15:29
He knows Русский it will be easier with that

**Comment by NDruce** [comment] 2016-05-10 17:15
Что ты процитировал, Богдан?

**Comment by Bogdan-G** [comment] 2016-05-10 22:13
@NDruce твой пост с картинками, я просто сделал две стрелки а маркдаун их переделал в цитату гг.

**Comment by NDruce** [comment] 2016-05-10 22:15
Что там с решением проблемы? Нашли?
What is about solving problem? Found?

**Comment by NDruce** [comment] 2016-05-10 22:16
All versions from tcpr.ca/cauldron

**Comment by NDruce** [comment] 2016-05-14 17:01
Only "location from" is broken. I think bug is in ThermiteTeleportationHandler.class

**Comment by Time6628** [comment] 2016-05-14 17:15
> Only "location from" is broken. I think bug is in ThermiteTeleportationHandler.class

Well if this bug affects every cauldron version, that is not the case because that class doesn't exist in cauldron or KCauldron.

**Comment by NDruce** [comment] 2016-05-14 18:31
Just debug all possible classes for worlds, I hope you find it. Not all versions, I wrote above what version was fine and attached screenshots with server version and worlds from/to

**Comment by linkinkov** [comment] 2016-05-20 22:14
possible revert bin patches from blood?

**Comment by Robotia** [comment] 2016-05-21 22:16
Ne, eto Forge 1614 :confused:

**Comment by Tencao** [comment] 2016-05-22 01:10
I really hope this bug gets fixed soon, also experiencing this when going to the nether, it's returning a completely different location than where the player is suppose to go.

**Comment by linkinkov** [comment] 2016-05-25 20:44
https://www.youtube.com/watch?v=MT1vffFxnS4 with this bug, possible create dupe of portals :)

**Comment by NDruce** [comment] 2016-05-25 21:44
Not only this. Mainly it possible to place blocks in Creative world inventory and use it from Survival world inventory. There are no inventory differents! GET FREE DIAMONDS, SHARE THEM AND BRAKE ALL THE SERVER ECONOMY! GET BEDROCK AND PLACE IT ANYWHERE, NOBODY CAN BREAK IT!

IT'S VERY HARMFUL AND DEVILISH BUG WHICH MUST BE FIXED ANYWAY AND FIRSTLY 😈

**Comment by Time6628** [comment] 2016-05-25 23:09
If you have a creative and survival world on your server already, you're doing it wrong :p.

**Comment by Tencao** [comment] 2016-05-25 23:30
Creative worlds are actually really good for creative plot based worlds such as the PlotMe Plugin, providing that the inventories properly separate. Back when I was using cauldron (before KCauldron) on 1.7.10, creative worlds worked perfectly, but with this bug I'm actually scared to recreate this again.

**Comment by Time6628** [comment] 2016-05-26 00:31
You should have separate servers if you want creative and survival mode worlds.

**Comment by Tencao** [comment] 2016-05-26 00:39
Alot of people cant afford to run two servers just for an optional game mode, especially for modded servers. Creative and Survival world have worked fine for ages prior to this bug, so while separate servers is a temp solution, it shouldn't be the only solution.

**Comment by Time6628** [comment] 2016-05-26 00:57
@NDruce Could you try this version? [[Link]](https://drive.google.com/open?id=0B-dYnjpJ0rVPLVBhMjlHWkRnN1E)

@Tencao If you can't afford it then don't do it. I'm just saying it's pretty "tacky" to have a creative plots world on a survival server.

**Comment by Tencao** [comment] 2016-05-26 01:08
It's not really tacky when it's worked so well for so long. Like I said, this has worked perfectly on spigot for years, and worked perfectly on cauldron for ages too until this bug came in.

**Comment by abaw7** [comment] 2016-05-26 01:42
If both Servers are linked and ran by the same staff team, it's actually tackier to require them to go to a different server, it appears unprofessional. Looking at Hosting companies: How many companies will tell you that you have to go to a website ran by the exact same exact team of people to buy a VPS because their POS doesn't handle VPSes, but handles dedicated servers just fine. The same applies here, asking people to go to a separate server for creative, when it's ran by the exact same people isn't very professional. While I agree that it's better practice to use bungeecord and link two servers together, a large majority of people don't have that option simply because that'd be a large cost that simply wouldn't be worth it. Saying that they're doing it wrong is not completely true because they're utilizing a proven method. Is it wrong for me to host a webserver and Minecraft server on the same machine as a teamspeak server? No, It's just not the most professional method of handling it.

**Comment by Bogdan-G** [comment] 2016-05-26 11:16
^ to put it simply - incompetent offer solutions to problems

**Comment by NDruce** [comment] 2016-05-29 18:27
Not fixed in Thermos 57 build

**Comment by Time6628** [comment] 2016-05-29 18:42
As I said, try the version I sent above.

**Comment by Time6628** [comment] 2016-05-29 18:43
https://drive.google.com/open?id=0B-dYnjpJ0rVPLVBhMjlHWkRnN1E

**Comment by NDruce** [comment] 2016-05-29 18:53
Not fixed. In future, test it yourself before releasing possible fix with my plugin [ChangeWorldDebug](https://www.dropbox.com/s/07sdezlpyorubps/ChangeWorldDebug.jar?dl=1)

**Comment by BungeeTheCookie** [comment] 2016-05-29 20:53
Tested the build, doesn't work.

**Comment by NDruce** [comment] 2016-05-29 21:31
@BungeeTheCookie, the same. Doesn't work.

**Closed** 2016-05-30 23:22 UTC
Labels: bug

**Comment by NDruce** [comment] 2016-05-30 23:32
Hey! What did you close that? Thermos is useless while this bug exists, because all the admins can host servers on (K)Cauldron 1307/1291. This bug is number one to be fixed. Just debug all classes which handle player world switching, it's hardly?

**Comment by Time6628** [comment] 2016-05-30 23:33
Because he fixed it.
