### ISSUE TITLE
Bug with scavenger. (DUP)

### ISSUE THREAD

**Issue by iNightmarei** [CyberdyneCC/Thermos#491] opened 2016-08-17 13:16 UTC
**Explanation of issue:**
When player was dead them items was drop but him items saved after respawn because on the server has a plugin "scavenger". Thereby items was dup.

**How to recreate this issue:**
You need to die with items when your items will be saved by "scavenger".

**Plugins Installed:**
"Scavenger"

**Thermos Version:** Build 57
**Forge Version:** 1.7.10-1614

**Video with dup: (YouTube)** https://www.youtube.com/watch?v=WSsVx5Apk88

P.S. On KCauldron in version 192 was fix this issue:

**From site (https://repo.prok.pw/pw/prok/KCauldron/1.7.10-1614.201/KCauldron-1.7.10-1614.201-changelog.txt):**

```
# 1.7.10-1614.192: 8427682
Fix inventory wiping on keepInventory=true
```

P.S.S. Sorry for my english.

**Comment by KasperFranz** [comment] 2016-08-17 15:32
Dupe of #451

**Closed** 2016-08-17 16:46 UTC
