### ISSUE TITLE
Pixelmon 1.7.10 server is die.

### ISSUE THREAD

**Issue by YuriySimakov** [CyberdyneCC/Thermos#520] opened 2016-09-13 09:59 UTC
[2016-09-13-7.txt](https://github.com/CyberdyneCC/Thermos/files/469449/2016-09-13-7.txt)

**Comment by KasperFranz** [comment] 2016-09-13 10:51
follow the template - it is there for a reason and might de dupe of #519

**Closed** 2016-09-13 12:57 UTC

**Comment by YuriySimakov** [comment] 2016-09-13 16:08
But

**Comment by Robotia** [comment] 2016-09-14 00:48
```follow the template```
